format = "$directory$git_branch$git_status$time$character"

add_newline = true

[directory]
style = "#7aa2f7"
format = "[ $path]($style) "
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "#bb9af7"
format = "[$symbol$branch]($style) "

[git_status]
style = "#f7768e"
format = "([$all_status$ahead_behind]($style)) "

[time]
disabled = false
time_format = "%H:%M:%S"
style = "#565f89"
format = "[ $time]($style) "

[character]
success_symbol = "[❯](#9ece6a)"
error_symbol = "[❯](#f7768e)"
