format = "$time$username$directory$git_branch$git_status$character"

add_newline = false

[username]
style_user = "#7dcfff"
style_root = "#f7768e"
format = "[$user]($style) in"
show_always = true

[directory]
style = "#7aa2f7"
format = "[ $path]($style) "
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "#bb9af7"
format = "on[$symbol$branch]($style) "

[git_status]
style = "#f7768e"
format = "([$all_status$ahead_behind]($style)) "

[time]
disabled = false
time_format = "[%H:%M:%S]"
style = "#787c99"
format = "[$time]($style) "

[character]
success_symbol = "[❯](#41a6b5)"
error_symbol = "[❯](#f7768e)"
